// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXWahIg1q-jBBIM0mj7WATVrDMBynemI',
    appId: '1:170910642039:web:a47491ed676e423ff4bb72',
    messagingSenderId: '170910642039',
    projectId: 'rodizioscore',
    authDomain: 'rodizioscore.firebaseapp.com',
    databaseURL: 'https://rodizioscore-default-rtdb.firebaseio.com',
    storageBucket: 'rodizioscore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hxoNbeCZgIkOQyYWFo-5ZMtlnkUa3W8',
    appId: '1:170910642039:android:34c0ff8dc7fb8ff7f4bb72',
    messagingSenderId: '170910642039',
    projectId: 'rodizioscore',
    databaseURL: 'https://rodizioscore-default-rtdb.firebaseio.com',
    storageBucket: 'rodizioscore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7cbRUsx4A4a3drrnvwhG995aCSsylN0',
    appId: '1:170910642039:ios:cf478111767ab83ff4bb72',
    messagingSenderId: '170910642039',
    projectId: 'rodizioscore',
    databaseURL: 'https://rodizioscore-default-rtdb.firebaseio.com',
    storageBucket: 'rodizioscore.firebasestorage.app',
    iosBundleId: 'com.example.rodizioStats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ7cbRUsx4A4a3drrnvwhG995aCSsylN0',
    appId: '1:170910642039:ios:cf478111767ab83ff4bb72',
    messagingSenderId: '170910642039',
    projectId: 'rodizioscore',
    databaseURL: 'https://rodizioscore-default-rtdb.firebaseio.com',
    storageBucket: 'rodizioscore.firebasestorage.app',
    iosBundleId: 'com.example.rodizioStats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXXWahIg1q-jBBIM0mj7WATVrDMBynemI',
    appId: '1:170910642039:web:49107680a678b805f4bb72',
    messagingSenderId: '170910642039',
    projectId: 'rodizioscore',
    authDomain: 'rodizioscore.firebaseapp.com',
    databaseURL: 'https://rodizioscore-default-rtdb.firebaseio.com',
    storageBucket: 'rodizioscore.firebasestorage.app',
  );

}